sudo: false
language: node_js
node_js:
   - stable
   - '0.12'
script:
   - npm run lint
env:
   - NODE_ENV=development
install:
   - npm install
cache:
   directories:
      - node_modules
git:
   depth: 1
