sudo: false
language: node_js
cache:
   directories:
      - node_modules
notifications:
   email: false
node_js:
   - '7'
   - '6'
   - '5'
   - '4'
   - '0.12'
script:
   - npm t
env:
   - NODE_ENV=development
install:
   - npm install
cache:
   directories:
      - node_modules
git:
   depth: 1
