sudo: false
language: node_js
env:
  - NODE_ENV=development
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
install:
  - npm install
before_script:
  - npm prune
script:
  - npm t
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
